services:
  - type: web
    name: yinka-web-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: yinka.settings