services:
  - type: web
    name: yinka-web-app
    env: python
    plan: free
    buildCommand: | pip install -r requirements.txt
    python manage.py collectstatic --noinput
    python manage.py makemigrations
    python manage.py migrate
    python manage.py createsuperuser --noinput
    --username yinkakayodeandco --email yinkakayode25@gmail.com || true
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: YinkaWebApp
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: yinkaAdmin
      - key: DJANGO_SUPERUSER_EMAIL
        value: yinkakayode25@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: yinkakayode@2025!
      - key: DJANGO_SETTINGS_MODULE
        value: yinka.settings
      
