# Generated by Django 5.1.3 on 2024-12-11 11:33

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home_service_img')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_what_we_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('real_estate', ckeditor_uploader.fields.RichTextUploadingField()),
                ('consultancy', ckeditor_uploader.fields.RichTextUploadingField()),
                ('project_mgt', ckeditor_uploader.fields.RichTextUploadingField()),
                ('asset_valuation', ckeditor_uploader.fields.RichTextUploadingField()),
                ('project_appraisal', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What We Do',
                'verbose_name_plural': 'What We Do',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='project_img')),
                ('client', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('time_frame', models.CharField(max_length=50)),
                ('extra_service', models.CharField(max_length=100)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='p_img')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projects')),
            ],
        ),
    ]
