# Generated by Django 5.1.3 on 2024-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_services',
            options={'ordering': ['name'], 'verbose_name': 'Home Service Section', 'verbose_name_plural': 'Home Service Section'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
    ]
