# Generated by Django 5.1.3 on 2024-12-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='pro_image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='other_image',
        ),
    ]
