# Generated by Django 5.1.3 on 2024-12-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_image_projects_pro_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='other_image',
            new_name='image',
        ),
    ]
