# Generated by Django 5.1.3 on 2024-12-12 10:32

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_other_image_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='service_img')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Page Content',
                'verbose_name_plural': 'Service PAge Content',
                'ordering': ['name'],
            },
        ),
    ]
