# Generated by Django 5.1.3 on 2025-01-07 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_staticservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticservices',
            options={'ordering': ['name'], 'verbose_name': 'Service Page Content', 'verbose_name_plural': 'Service Page Content'},
        ),
        migrations.AddField(
            model_name='home_what_we_do',
            name='property_management',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
