# Generated by Django 5.1.3 on 2025-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_staticservices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_what_we_do',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
