# Generated by Django 5.1.3 on 2025-05-19 12:16

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_home_what_we_do_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home_service_img')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Success Section',
                'verbose_name_plural': 'Home Success Section',
                'ordering': ['company_name'],
            },
        ),
    ]
